package entity;
// Generated Feb 20, 2017 9:00:37 AM by Hibernate Tools 4.3.1



/**
 * Reg generated by hbm2java
 */
public class Reg  implements java.io.Serializable {


     private String username;
     private String password;
     private String lastname;
     private Boolean isadmin;

    public Reg() {
    }

	
    public Reg(String username, String password) {
        this.username = username;
        this.password = password;
    }
    public Reg(String username, String password, String lastname, Boolean isadmin) {
       this.username = username;
       this.password = password;
       this.lastname = lastname;
       this.isadmin = isadmin;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public Boolean getIsadmin() {
        return this.isadmin;
    }
    
    public void setIsadmin(Boolean isadmin) {
        this.isadmin = isadmin;
    }




}


